language: generic

git:
  submodules: false

env:
  global:
    - WORKSPACE=Example/Coherence.xcworkspace
    - SCHEME=Coherence-Example

matrix:
  include:
    -
      os: osx
      osx_image: xcode8
      env: 
         - BUILD="pod lint"
    - 
      os: osx
      osx_image: xcode8
      env: 
         - BUILD="xcodebuild"
         - TEST_DEST="platform=iOS Simulator,OS=10.0,name=iPhone 6s" 
         - TEST_SDK=iphonesimulator
    - 
      os: osx
      osx_image: xcode8
      env: 
         - BUILD="xcodebuild"
         - TEST_DEST="platform=iOS Simulator,OS=10.0,name=iPhone 6" 
         - TEST_SDK=iphonesimulator
    - 
      os: osx
      osx_image: xcode8
      env: 
         - BUILD="xcodebuild"
         - TEST_DEST="platform=iOS Simulator,OS=9.3,name=iPhone 6" 
         - TEST_SDK=iphonesimulator
    - 
      os: osx
      osx_image: xcode8
      env: 
         - BUILD="xcodebuild"
         - TEST_DEST="platform=iOS Simulator,OS=9.2,name=iPhone 5s" 
         - TEST_SDK=iphonesimulator

    - 
      os: osx
      osx_image: xcode8
      env: 
         - BUILD="xcodebuild"
         - TEST_DEST="platform=iOS Simulator,OS=9.0,name=iPhone 4s" 
         - TEST_SDK=iphonesimulator

before_install:
  #
  # If there is a Gemfile for this os, install bundler and ask bundler to install the gems
  #
  - |
    if [ -e Gemfile."$TRAVIS_OS_NAME" ]; then
       export BUNDLE_GEMFILE=Gemfile."$TRAVIS_OS_NAME"
       gem install bundler
       bundler install
    fi

script:
  - set -e
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
       # Fix travis issue: https://github.com/travis-ci/travis-ci/issues/6307
       rvm get head --auto-dotfiles || true
    fi
  - |
    if [[ "$BUILD" == "swift build"  ]]; then
      set -e
      swift test
      set +e
    fi
  - |
    if [[ "$BUILD" == "pod lint" ]]; then
        set -e
        bundler exec pod repo update
        bundler exec pod lib lint
        set +e
    fi
  - |
    if [[ "$BUILD" == "xcodebuild"  ]]; then
        set -e
        set -o pipefail
        xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$TEST_DEST" -sdk "$TEST_SDK" -enableCodeCoverage YES build-for-testing | bundler exec xcpretty
        xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$TEST_DEST" -sdk "$TEST_SDK" -enableCodeCoverage YES test              | bundler exec xcpretty
        set +o pipefail
        set +e
    fi
  - set +e

after_success:
  - bash <(curl -s https://codecov.io/bash)
