

comment:
  layout: header, changes, diff
coverage:
  ignore:
  - Example/.*
  - Scripts/.*
  - Docs/.*
  - Pods/.*
  - Pod/Internal/.*
  - Pod/Cache/Internal/.*
  - Applications/Xcode.app/.*
  - vendor/.*
  - Carthage/.*
  - build/.*
  - .build/.*
  - .vagrant/.*
  - Tests/.*
  status:
    patch: false
